web:
  build: .
  command: node index-db.js
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    MYSQL_DATABASE: ait
    MYSQL_USER: devops
    MYSQL_PASSWORD: devops
    MYSQL_HOST: db
db:
  image: orchardup/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: ait
    MYSQL_USER: devops
    MYSQL_PASSWORD: devops
